const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const oldGates = `const DEFAULT_STRATEGY_GATES: Record<StrategyType, StrategyGates> = {
  BTC_TREND: {
    hurst: 0.55,
    fisher: 1.5,
    rSquared: 0.4,
    dvol: 50,
    toxicity: 0.7,
    slippage: 0.001,
    vwapZScore: 2.0,
    ofi: 0.2,
    volRatio: 1.5,
  },
  BTC_MEAN_REV: {
    hurst: 0.4,
    fisher: 2.0,
    rSquared: 0.3,
    dvol: 40,
    toxicity: 0.5,
    slippage: 0.001,
    vwapZScore: 2.5,
    ofi: 0.1,
    volRatio: 1.2,
  },
  BTC_TREND_FOLLOWING: {
    hurst: 0.6,
    fisher: 1.0,
    rSquared: 0.5,
    dvol: 60,
    toxicity: 0.8,
    slippage: 0.001,
    vwapZScore: 1.5,
    ofi: 0.3,
    volRatio: 1.8,
  },
  BTC_OFI: {
    hurst: 0.5,
    fisher: 1.0,
    rSquared: 0.4,
    dvol: 50,
    toxicity: 0.6,
    slippage: 0.001,
    vwapZScore: 2.0,
    ofi: 0.5,
    volRatio: 1.5,
  },
  BTC_AVR: {
    hurst: 0.5,
    fisher: 1.0,
    rSquared: 0.4,
    dvol: 50,
    toxicity: 0.6,
    slippage: 0.001,
    vwapZScore: 2.0,
    ofi: 0.2,
    volRatio: 1.5,
  },
  BTC_SCALPER: {
    hurst: 0.4,
    fisher: 1.5,
    rSquared: 0.3,
    dvol: 40,
    toxicity: 0.5,
    slippage: 0.001,
    vwapZScore: 2.5,
    ofi: 0.1,
    volRatio: 1.2,
  },`;

const newGates = `const DEFAULT_STRATEGY_GATES: Record<StrategyType, StrategyGates> = {
  BTC_TREND: {
    hurst: 0.55,
    fisher: 1.2,
    rSquared: 0.3,
    dvol: 40,
    toxicity: 0.7,
    slippage: 0.001,
    vwapZScore: 1.5,
    ofi: 0.2,
    volRatio: 1.2,
  },
  BTC_MEAN_REV: {
    hurst: 0.4,
    fisher: 1.5,
    rSquared: 0.2,
    dvol: 30,
    toxicity: 0.5,
    slippage: 0.001,
    vwapZScore: 2.0,
    ofi: 0.1,
    volRatio: 1.1,
  },
  BTC_TREND_FOLLOWING: {
    hurst: 0.6,
    fisher: 0.8,
    rSquared: 0.4,
    dvol: 45,
    toxicity: 0.8,
    slippage: 0.001,
    vwapZScore: 1.2,
    ofi: 0.3,
    volRatio: 1.5,
  },
  BTC_OFI: {
    hurst: 0.5,
    fisher: 1.0,
    rSquared: 0.3,
    dvol: 40,
    toxicity: 0.6,
    slippage: 0.001,
    vwapZScore: 1.5,
    ofi: 0.4,
    volRatio: 1.2,
  },
  BTC_AVR: {
    hurst: 0.5,
    fisher: 1.0,
    rSquared: 0.3,
    dvol: 40,
    toxicity: 0.6,
    slippage: 0.001,
    vwapZScore: 1.5,
    ofi: 0.2,
    volRatio: 1.2,
  },
  BTC_SCALPER: {
    hurst: 0.4,
    fisher: 1.2,
    rSquared: 0.2,
    dvol: 30,
    toxicity: 0.5,
    slippage: 0.001,
    vwapZScore: 2.0,
    ofi: 0.1,
    volRatio: 1.1,
  },`;

code = code.replace(oldGates, newGates);
fs.writeFileSync('src/App.tsx', code);
console.log("Updated BTC strategy gates");
